@Library("jenlib") _

wafDefaultPipeline(projects: ["verilog-i2c"],
                   container: [image: getDefaultAsicContainerPath(),
                               app: "asic"],
                   enableClangFormat: false,
                   enableClangTidy: false,
                   enableCppcheck: false,
                   notificationChannel: "#dls-fpga")
